F branch
Maclenn77/Newsweek_clone_bootstrap pull request #3
Opened 2020-03-21 00:29 UTC by Maclenn77

In this project, I created a clone of Newsweek using bootstrap. This website has:
-   One navbar with a toggle menu for sm and md sizes.
-     A main section with many different articles. Each article rearrange in each breakpoint
-     A footer with other info from the website.

I used media queries and bootstrap for a responsive design with two breakpoints. Thank you for reviewing!

2020-03-21 01:25 UTC, uryelah commented
Hello ** J. P. Pérez**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all good job at for a first PR.🎇**
Great use of semantic HTML and attention to colors!

There are still some issues to work through so hang in there 💪 

---------    

### Required changes 🛠 
---------

- [ ] Since a lot of the responsiveness and style are being handled by Bootstrap this project needs to be as close as possible to the original site. This includes **spacing**, **positioning** and **font style and weight**. Compare your clone and [the original site ](https://www.newsweek.com/)
carefully and find the differences in style so they can get fixed.

- [ ] The original site doesn't take 100% of the width after a certain window size. Compare you version and the original site bellow:
![Screenshot_2020-03-20 Newsweek clone](https://user-images.githubusercontent.com/16193212/77216161-3f519900-6af7-11ea-9975-a20347c12b36.png)

**Original:**
![Screenshot_2020-03-20 Newsweek(13)](https://user-images.githubusercontent.com/16193212/77216165-45e01080-6af7-11ea-9b9c-7765ff27ec18.png)
-------

- [ ] Your whole layout, but the navbar and footer, is breaking at screens smaller or equal to 991px of width. Try to fix that using mainly Boostrap responsive grid system. [Check this article about it here.](https://uxplanet.org/how-the-bootstrap-4-grid-works-a1b04703a3b7)
![Screenshot_2020-03-20 Newsweek clone(1)](https://user-images.githubusercontent.com/16193212/77216248-c3a41c00-6af7-11ea-80a3-5da7b27ccf55.png)

-------

- [ ] There's a slight horizontal scroll in your whole site's body in wide screens. Please fix that overflow issue.

- [ ] Try to style the navbar search bar in a similar fashion to the original one.
![Screenshot_2020-03-20 Newsweek clone(2)](https://user-images.githubusercontent.com/16193212/77216331-4fb64380-6af8-11ea-8d60-a41971406dfd.png)
**Original search:**
![Screenshot_2020-03-20 Newsweek(14)](https://user-images.githubusercontent.com/16193212/77216339-59d84200-6af8-11ea-9dbc-3b765b1c30f7.png)

--------

- [ ] Make sure that the 'Featured Stories', 'Top story', and 'Opinion' sections have margins between them. Look for a way to add margins with Bootstrap classes.

- [ ] At the 'Opinion' section add pictures of the colonists that are equal from the ones in the original site.
**Your pictures**
![Screenshot_2020-03-20 Newsweek clone(3)](https://user-images.githubusercontent.com/16193212/77216408-d10dd600-6af8-11ea-84d2-cfc5617a40b6.png)

**Original ones**
![Screenshot_2020-03-20 Newsweek(15)](https://user-images.githubusercontent.com/16193212/77216409-d23f0300-6af8-11ea-98ad-e3bc990f0825.png)

--------

- [ ] The 'Newsletter' image should remain proportional and not distorted regardless of the screen size. Fix it so it's not distorted anymore.
![Screenshot_2020-03-20 Newsweek clone(4)](https://user-images.githubusercontent.com/16193212/77216438-1b8f5280-6af9-11ea-9c29-454682eabc55.png)

**Original one:**
![Screenshot_2020-03-20 Newsweek(16)](https://user-images.githubusercontent.com/16193212/77216440-1e8a4300-6af9-11ea-8c40-2db529289ac7.png)

----------

## Optional Improvements

- [ ] [OPTIONAL] Put a screenshot of your clone in your readme file to show off your work

--------

I share the sentiment that _Bootstrap is ok_ and I know that parsing through the documentation can be frustrating at times, I really like [cheat-sheet](https://hackerthemes.com/bootstrap-cheatsheet/) for my own workflow, but if you give yourself some time to play around with the classes and test how they work I think you'll be pleasantly surprised about how bootstrap can make responsiveness practical.
This project is on the bigger side but I'm sure you'll be able to nail it!

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-23 23:46 UTC, Maclenn77 commented
Thanks a lot, @uryelah ! It has been the best code review that I've received.
The Cheatsheet and the link that you shared were really useful.
I've done the changes and I hope there's any missing.

2020-03-24 00:42 UTC, majovanilla requested changes
Hey @Maclenn77 :wave: 

## Good job implementing the required changes on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- [x] The previous TSE required you to check the general width of your body elements to match the original page. You used grid to achieve a similar look, but you should take a look at the `container-fluid` bootstrap class and use `col-*` in a responsive way to control the width of the body in the different breakpoint.

- [x] You are not using bootstrap classes **everywhere**. This is a [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) 

- [x] Properties like width, height, padding, and margin should be all over your HTML file and not in your CSS. You **are not using enough col-* classes** and this is the best feature bootstrap has!

- [x] I commented **some** of your CSS classes so that you change them for bootstrap classes. There is a lot more to change but I didn't mention them to avoid repetition. Focus on the properties mentioned above.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-24 00:42 UTC, majovanilla commented on README.md
> +Newsweek is one of many site that uses Bootstrap for its design.
- [ ] Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more info.

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +      </div>
- [ ] Your navbar has more height than the original one. Please make the adjustment.

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +        </ul>
- [ ] The navbar menus are not displaying like the original page. You should check the width of the `<ul>` element and make it look like the original page.

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +        <h2 class="text-weight-bold">Bootstrap makes building a site faster, developers say</h2>
- [ ] The elements inside your `<main>` tag should have more margin to the sides. Please use bootstrap classes for this.

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +                Tech & Science
- [ ] The badges you are using inside the images of this section should be located on the bottom-left corner of the image. Try using `position: absolute` to keep them inside the image. Check this out in the Slideshows section, too.

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +          <img src="img/bootstrap.png" alt="Image Debate" class="float-left mr-4">
- [ ] The articles in this section have a larger image when you are in the medium breakpoint and below. Please adjust them.

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +        <section class="d-flex">
- [ ]  The images in this section are larger in the medium and small breakpoints. Also, check the font-size and adjust it.

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +          <section class="border-top d-flex">
- [ ] The articles in this section have a larger image when you are in the medium breakpoint and below. Please adjust them.

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +      </article>
- [ ] The elements in this section are not behaving as expected. Check the image below and see how the newsletter is overflowing the body of your page. If you make use of the suggested classes in the body, you might be able to solve this problem.

- [ ] You are not using the `col-*` class in these elements. You should take advantage of the bootstrap classes to achieve the desired design.

![Screenshot from 2020-03-23 18-31-34](https://user-images.githubusercontent.com/51926937/77375987-b9bb2c80-6d34-11ea-8d3c-a77a8d26d77a.png)

Original:
![Screenshot from 2020-03-23 18-33-29](https://user-images.githubusercontent.com/51926937/77376013-cfc8ed00-6d34-11ea-8953-a92ae97be2e5.png)

2020-03-24 00:42 UTC, majovanilla commented on index.html
> +  </footer>
- [ ] The footer has a 100% width and it should have the same width as the rest of the page (not including the navbar). Please make the adjustment.

2020-03-24 00:42 UTC, majovanilla commented on styles/style.css
> +}
- [ ] You should use bootstrap classes.

2020-03-24 00:42 UTC, majovanilla commented on styles/style.css
> +}
- [ ] - [ ] You should use bootstrap classes.

2020-03-24 00:42 UTC, majovanilla commented on styles/style.css
> +  margin-top: 2rem;
- [ ] You should use bootstrap classes.

2020-03-24 00:42 UTC, majovanilla commented on styles/style.css
> +  font-weight: bold !important;
- [ ] You should use bootstrap classes.

2020-03-24 00:42 UTC, majovanilla commented on styles/style.css
> +  position: absolute;
- [ ] You should use bootstrap classes.

2020-03-26 00:11 UTC, uryelah commented
Hi **J. P. Pérez**, I'm Sarah, back to review this PR 👩‍🚀

You did a great deal of progress since the first review! Good job, really! 🎆 

There are still some style and spacing issues left since, as mentioned before, this project requires a lot of attention to detail. You already did the hardest part though so lets check what's next 💪 

------

## Required changes 🛠 
---------

- [ ] All the sections above 'In the Magazine' need to be aligned at the bottom without any extra empty space. To reach that you can try using the 'overflow' property and set it to scroll vertically. Try to figure out how to hide the scrollbar though.
![Screenshot_2020-03-25 Newsweek(31)](https://user-images.githubusercontent.com/16193212/77596825-df366a80-6edb-11ea-8c31-5847a1db3ae1.png)
**Original site:**
![Screenshot_2020-03-25 Newsweek clone(2)](https://user-images.githubusercontent.com/16193212/77596829-e0679780-6edb-11ea-9196-0f4324c19488.png)

-----

- [ ] Good job changing the color of the menu icon, it's really hard to see it right now so try to make it a bit more contrasting. Compare your version and the original one below:

![Screenshot_2020-03-25 Newsweek clone(3)](https://user-images.githubusercontent.com/16193212/77596831-e1002e00-6edb-11ea-8aa1-f1fc734ef4a8.png)
![Screenshot_2020-03-25 Newsweek(32)](https://user-images.githubusercontent.com/16193212/77596832-e198c480-6edb-11ea-8090-e5abede562f9.png)

----

- [ ] On medium to small screens the page content takes 100% of the window width:
**Your version still has margins:**
![Screenshot_2020-03-25 Newsweek clone(4)](https://user-images.githubusercontent.com/16193212/77596833-e198c480-6edb-11ea-8bf3-efab1684dad2.png)
**Original version:**
![Screenshot_2020-03-25 Newsweek(33)](https://user-images.githubusercontent.com/16193212/77596835-e2c9f180-6edb-11ea-802a-d8d2c3afc6e3.png)

-----

- [ ] In medium and small-sized screens some of your images, like the ones from the 'Opinion' section are too big. Check the original site again and make sure they are closer to the original proportion displayed in the specific screen sizes.

![Screenshot_2020-03-25 Newsweek clone(5)](https://user-images.githubusercontent.com/16193212/77596838-e3628800-6edb-11ea-902d-fcfe033a8ac8.png)
![Screenshot_2020-03-25 Newsweek(34)](https://user-images.githubusercontent.com/16193212/77596840-e3628800-6edb-11ea-8311-910a9f69384b.png)

---- 

- [ ] Make sure you use the same images, or similar ones, in each section header. Compare bellow the 'N' red squares you added and the original ones:


![Screenshot_2020-03-25 Newsweek clone(6)](https://user-images.githubusercontent.com/16193212/77596842-e3fb1e80-6edb-11ea-88a1-aa30dae6bb06.png)
![Screenshot_2020-03-25 Newsweek(35)](https://user-images.githubusercontent.com/16193212/77596844-e493b500-6edb-11ea-90a4-2a5be1676b30.png)


![Screenshot_2020-03-25 Newsweek clone(7)](https://user-images.githubusercontent.com/16193212/77596845-e52c4b80-6edb-11ea-9a00-25fd1c7774e6.png)
![Screenshot_2020-03-25 Newsweek(36)](https://user-images.githubusercontent.com/16193212/77596846-e52c4b80-6edb-11ea-935b-9a4d0d3beac4.png)

----

- [ ] On wide screens the footer must have the same width as the content of the site, not 100% of the window width:
![Screenshot_2020-03-25 Newsweek clone](https://user-images.githubusercontent.com/16193212/77596847-e5c4e200-6edb-11ea-810f-011b7e0a7d80.png)
![Screenshot_2020-03-25 Newsweek(29)](https://user-images.githubusercontent.com/16193212/77596849-e65d7880-6edb-11ea-9f51-6401a10600ce.png)


---

- [ ] Make sure the 'Latest News' images don't get distorted on resize and keep their proportions, compare your version and the origina site:
![Screenshot_2020-03-25 Newsweek clone(1)](https://user-images.githubusercontent.com/16193212/77596851-e65d7880-6edb-11ea-8948-87427bd0fbed.png)
![Screenshot_2020-03-25 Newsweek(30)](https://user-images.githubusercontent.com/16193212/77596824-de053d80-6edb-11ea-95ab-8f18d8d34154.png)

---------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-26 21:02 UTC, men32z requested changes
## Good job on this project and making changes! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

* [x] In the previous review one of my colleagues mentioned something about color, you can use a tool to pick colors on your browser, try to search "firefox colorpicker" or "chrome colorpicker" there are good tools, you can also inspect the code of the original page until you found the color amoung the clases.  right now I'm going to tell you specifically the color is #f72210

* [x] you did great with the margins for mobile but now the full width version has the 100% of the with and should have the same limit as all page. 
#### original version
![Screenshot_2020-03-26 Newsweek](https://user-images.githubusercontent.com/9115996/77695817-fd4eaa00-6f71-11ea-8c40-c24b1f0855c9.png)
#### your version 
![Screenshot_2020-03-26 Newsweek clone](https://user-images.githubusercontent.com/9115996/77695823-fe7fd700-6f71-11ea-8b57-3e355d5b5b65.jpg)

* [x] good job on this change, just try to make it even better by changin the mobile font size and weight(bold)
![Screenshot_2020-03-26 Newsweek clone](https://user-images.githubusercontent.com/9115996/77695981-43a40900-6f72-11ea-8050-6cef5a9908f0.png)

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help!

--Luis Preza

2020-03-27 02:06 UTC, davidmrtz-dev approved these changes
### **Status: Approved.** ✅ 
****
### Hi @Maclenn77 . 😄 
****
Awesome job!, You correctly implemented all the specifications required by the previous TSE's and your project looks awesome and shows that you know what are you doing 😎 
Congratulations! 👍 
You can merge this branch and move onto the next project. 🎊 
Happy coding! 😄 💻  
****
**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

2020-03-27 14:19 UTC, merged